### ISSUE TITLE
[Bug] Drop files DOM error

### ISSUE THREAD

**Issue by ealejandro101** [creativetimofficial/ct-nuxt-argon-dashboard-pro#15]
### Version
1.2.1
### Reproduction link
https://demos.creative-tim.com/nuxt-argon-dashboard-pro/forms/components
### Operating System
Win 10
### Device
Desktop
### Browser & Version
Chrome Versión 80.0.3987.132 (Build oficial) (64 bits)
### Steps to reproduce
1. I add a file in DropZone multiple files
2. Inspect the console debug
3. The error in console is:

c9e73c1111eeb1b8fa0e.js:1 Uncaught DOMException: Failed to execute 'open' on 'XMLHttpRequest': Invalid URL
    at l.value (https://demos.creative-tim.com/nuxt-argon-dashboard-pro/_nuxt/c9e73c1111eeb1b8fa0e.js:1:31135)
    at https://demos.creative-tim.com/nuxt-argon-dashboard-pro/_nuxt/c9e73c1111eeb1b8fa0e.js:1:30667
    at https://demos.creative-tim.com/nuxt-argon-dashboard-pro/_nuxt/c9e73c1111eeb1b8fa0e.js:1:32279
    at l.transformFile (https://demos.creative-tim.com/nuxt-argon-dashboard-pro/_nuxt/c9e73c1111eeb1b8fa0e.js:1:7688)
    at l (https://demos.creative-tim.com/nuxt-argon-dashboard-pro/_nuxt/c9e73c1111eeb1b8fa0e.js:1:32231)
    at l.value (https://demos.creative-tim.com/nuxt-argon-dashboard-pro/_nuxt/c9e73c1111eeb1b8fa0e.js:1:32307)
    at l.value (https://demos.creative-tim.com/nuxt-argon-dashboard-pro/_nuxt/c9e73c1111eeb1b8fa0e.js:1:29679)
    at l.value (https://demos.creative-tim.com/nuxt-argon-dashboard-pro/_nuxt/c9e73c1111eeb1b8fa0e.js:1:28665)
    at l.value (https://demos.creative-tim.com/nuxt-argon-dashboard-pro/_nuxt/c9e73c1111eeb1b8fa0e.js:1:28414)
    at l.value (https://demos.creative-tim.com/nuxt-argon-dashboard-pro/_nuxt/c9e73c1111eeb1b8fa0e.js:1:28333)
value @ c9e73c1111eeb1b8fa0e.js:1
(anonymous) @ c9e73c1111eeb1b8fa0e.js:1
(anonymous) @ c9e73c1111eeb1b8fa0e.js:1
transformFile @ c9e73c1111eeb1b8fa0e.js:1
l @ c9e73c1111eeb1b8fa0e.js:1
value @ c9e73c1111eeb1b8fa0e.js:1
value @ c9e73c1111eeb1b8fa0e.js:1
value @ c9e73c1111eeb1b8fa0e.js:1
value @ c9e73c1111eeb1b8fa0e.js:1
value @ c9e73c1111eeb1b8fa0e.js:1
(anonymous) @ c9e73c1111eeb1b8fa0e.js:1
setTimeout (async)
value @ c9e73c1111eeb1b8fa0e.js:1
(anonymous) @ c9e73c1111eeb1b8fa0e.js:1
accept @ c9e73c1111eeb1b8fa0e.js:1
value @ c9e73c1111eeb1b8fa0e.js:1
value @ c9e73c1111eeb1b8fa0e.js:1
(anonymous) @ c9e73c1111eeb1b8fa0e.js:1

### What is expected?
Solution this bug
### What is actually happening?
The app have an client error

---

**Comment by sajadevo** [comment]
Hey there,

We just update the product to nuxt 3, you can update it to the latest version to get the final updates.

Regards,
Sajad
